import SwiftUI
import HealthKit
import Charts

// MARK: - AudiogramView
// Displays audiogram data from HealthKit — hearing threshold measurements across
// standard frequencies for left and right ears. Audiograms can be generated by
// iPhone's Hearing Test feature (iOS 18+ via AirPods Pro 2 or compatible headphones)
// or imported from clinical records.
//
// Science:
//   WHO 2021 (World Hearing Report): 1.5 billion people worldwide live with some
//     degree of hearing loss. Early detection at 4–8 kHz reveals noise damage
//     before it reaches speech frequencies.
//   Kähäri et al. 2003 (Scand J Work Environ Health): musicians show greatest loss
//     at 6 kHz — the "noise notch" characteristic of noise-induced hearing loss (NIHL).
//     Classical musicians lose 3–8 dB more than matched controls by age 40.
//   Liberman 2015 (J Neurosci): cochlear synaptopathy ("hidden hearing loss") —
//     high-frequency thresholds may appear normal while nerve fiber loss is already
//     significant. Regular audiograms track overt threshold shift before symptoms appear.
//   NIOSH 1998: ≥85 dB(A) for 8 hours/day exceeds safe noise exposure;
//     each 3 dB increase halves permissible exposure duration.
//
// Audiogram reading:
//   0–15 dBHL:  Normal hearing
//   16–25 dBHL: Slight loss (minimal, rarely noticed)
//   26–40 dBHL: Mild loss (speech understanding affected in noise)
//   41–55 dBHL: Moderate loss (speech difficult without amplification)
//   >55 dBHL:   Significant loss (hearing aid needed)
//
// Standard frequencies tested: 250, 500, 1000, 2000, 3000, 4000, 6000, 8000 Hz.

struct AudiogramView: View {

    // MARK: - Models

    struct Audiogram: Identifiable {
        let id = UUID()
        let date: Date
        let label: String
        let points: [FreqPoint]

        struct FreqPoint: Identifiable {
            let id = UUID()
            let freqHz: Double
            let leftDBHL: Double?
            let rightDBHL: Double?

            var freqLabel: String {
                freqHz >= 1000 ? "\(Int(freqHz/1000))k" : "\(Int(freqHz))"
            }
        }

        var worstThreshold: Double {
            let all = points.compactMap { max($0.leftDBHL ?? 0, $0.rightDBHL ?? 0) }
            return all.max() ?? 0
        }

        var hearingClass: HearingClass {
            switch worstThreshold {
            case ..<16:  return .normal
            case 16..<26: return .slight
            case 26..<41: return .mild
            case 41..<56: return .moderate
            default:      return .significant
            }
        }

        var hasNoiseNotch: Bool {
            // Look for notch at 4–6 kHz (worse than 2 kHz and 8 kHz)
            guard let p4k = points.first(where: { abs($0.freqHz - 4000) < 500 }),
                  let p2k = points.first(where: { abs($0.freqHz - 2000) < 300 }),
                  let p8k = points.first(where: { abs($0.freqHz - 8000) < 500 })
            else { return false }
            let worst4k = max(p4k.leftDBHL ?? 0, p4k.rightDBHL ?? 0)
            let best2k  = min(p2k.leftDBHL ?? 100, p2k.rightDBHL ?? 100)
            let best8k  = min(p8k.leftDBHL ?? 100, p8k.rightDBHL ?? 100)
            return worst4k > best2k + 10 && worst4k > best8k + 5
        }
    }

    enum HearingClass: String {
        case normal     = "Normal"
        case slight     = "Slight Loss"
        case mild       = "Mild Loss"
        case moderate   = "Moderate Loss"
        case significant = "Significant Loss"

        var color: Color {
            switch self {
            case .normal:      return .green
            case .slight:      return .blue
            case .mild:        return .yellow
            case .moderate:    return .orange
            case .significant: return .red
            }
        }
    }

    // MARK: - State

    @State private var audiograms: [Audiogram] = []
    @State private var isLoading = true

    private let healthStore = HKHealthStore()

    // MARK: - Body

    var body: some View {
        ScrollView {
            VStack(spacing: 16) {
                if isLoading {
                    ProgressView("Reading audiogram data…")
                        .padding(.top, 60)
                } else if audiograms.isEmpty {
                    noDataCard
                } else {
                    if let latest = audiograms.last {
                        classificationCard(latest)
                        audiogramChart(latest)
                        if latest.hasNoiseNotch {
                            noiseNotchCard
                        }
                    }
                    if audiograms.count > 1 {
                        historyCard
                    }
                    scienceCard
                }
            }
            .padding(.vertical)
        }
        .navigationTitle("Audiogram")
        .toolbarTitleDisplayMode(.inline)
        .task { await loadData() }
        .refreshable { await loadData() }
    }

    // MARK: - Classification Card

    private func classificationCard(_ a: Audiogram) -> some View {
        let cls = a.hearingClass

        return VStack(spacing: 14) {
            HStack(spacing: 0) {
                statBox(
                    value: String(format: "%.0f dBHL", a.worstThreshold),
                    label: "Worst Threshold",
                    sub: cls.rawValue,
                    color: cls.color
                )
                Divider().frame(height: 44)
                statBox(
                    value: a.label,
                    label: "Last Test",
                    sub: "audiogram date",
                    color: .blue
                )
                Divider().frame(height: 44)
                statBox(
                    value: "\(audiograms.count)",
                    label: "Tests on File",
                    sub: "in Health",
                    color: .purple
                )
            }
            .padding(.vertical, 12)

            HStack {
                Image(systemName: cls == .normal ? "ear.fill" : "exclamationmark.circle")
                    .foregroundStyle(cls.color)
                Text(classificationMessage(cls))
                    .font(.caption)
                    .foregroundStyle(cls.color)
            }
            .padding(.horizontal)
            .padding(.bottom, 8)
        }
        .background(Color(.secondarySystemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .padding(.horizontal)
    }

    private func classificationMessage(_ cls: HearingClass) -> String {
        switch cls {
        case .normal:      return "Normal hearing thresholds. Continue protecting hearing with <85 dB daily exposure."
        case .slight:      return "Slight hearing loss. Typically not noticeable but worth monitoring annually."
        case .mild:        return "Mild hearing loss. Speech understanding may be affected in noisy environments."
        case .moderate:    return "Moderate hearing loss. Consultation with an audiologist is recommended."
        case .significant: return "Significant hearing loss. Professional audiological evaluation advised."
        }
    }

    // MARK: - Audiogram Chart

    private func audiogramChart(_ a: Audiogram) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Label("Hearing Threshold by Frequency", systemImage: "waveform")
                .font(.subheadline).bold()
            Text("Lower dBHL = better hearing. Normal range: 0–15 dBHL (shaded). High-frequency loss (2–8 kHz) is typically the first sign of noise damage.")
                .font(.caption2).foregroundStyle(.secondary)

            let sorted = a.points.sorted { $0.freqHz < $1.freqHz }

            Chart {
                // Normal range band (0–15 dBHL)
                ForEach(sorted) { p in
                    AreaMark(
                        x: .value("Freq", p.freqLabel),
                        yStart: .value("Min", 0.0),
                        yEnd: .value("Max", 15.0)
                    )
                    .foregroundStyle(Color.green.opacity(0.08))
                }

                // Left ear
                ForEach(sorted.filter { $0.leftDBHL != nil }) { p in
                    LineMark(
                        x: .value("Freq", p.freqLabel),
                        y: .value("dBHL", p.leftDBHL!),
                        series: .value("Ear", "Left")
                    )
                    .foregroundStyle(Color.blue.gradient)
                    .symbol(.circle)

                    PointMark(
                        x: .value("Freq", p.freqLabel),
                        y: .value("dBHL", p.leftDBHL!)
                    )
                    .foregroundStyle(Color.blue)
                }

                // Right ear
                ForEach(sorted.filter { $0.rightDBHL != nil }) { p in
                    LineMark(
                        x: .value("Freq", p.freqLabel),
                        y: .value("dBHL", p.rightDBHL!),
                        series: .value("Ear", "Right")
                    )
                    .foregroundStyle(Color.red.gradient)
                    .symbol(.triangle)

                    PointMark(
                        x: .value("Freq", p.freqLabel),
                        y: .value("dBHL", p.rightDBHL!)
                    )
                    .foregroundStyle(Color.red)
                }

                // 25 dBHL mild loss threshold
                RuleMark(y: .value("Mild threshold", 25.0))
                    .foregroundStyle(Color.orange.opacity(0.4))
                    .lineStyle(StrokeStyle(lineWidth: 1, dash: [4, 3]))
                    .annotation(position: .trailing, alignment: .leading) {
                        Text("Mild").font(.caption2).foregroundStyle(.orange)
                    }
            }
            .frame(height: 200)
            .chartYScale(domain: -5...max(70, (a.points.compactMap { max($0.leftDBHL ?? 0, $0.rightDBHL ?? 0) }.max() ?? 30) + 10))
            .chartYAxisLabel("dBHL (lower = better)")
            .chartForegroundStyleScale(["Left": Color.blue, "Right": Color.red])

            HStack(spacing: 16) {
                Label("Left ear", systemImage: "circle.fill").foregroundStyle(.blue).font(.caption2)
                Label("Right ear", systemImage: "triangle.fill").foregroundStyle(.red).font(.caption2)
                Spacer()
                Text("Normal: 0–15 dBHL").font(.caption2).foregroundStyle(.secondary)
            }
        }
        .padding()
        .background(Color(.secondarySystemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .padding(.horizontal)
    }

    // MARK: - Noise Notch Card

    private var noiseNotchCard: some View {
        VStack(alignment: .leading, spacing: 8) {
            Label("Noise Notch Detected at 4–6 kHz", systemImage: "exclamationmark.triangle.fill")
                .font(.subheadline).bold()
                .foregroundStyle(.orange)
            Text("The 4–6 kHz dip (\"noise notch\") is the classic fingerprint of noise-induced hearing loss (NIHL). High-frequency hair cells in the cochlea are most vulnerable to acoustic trauma.")
                .font(.caption).foregroundStyle(.secondary)
            Text("Kähäri et al. 2003 (Scand J Work Environ Health): musicians show this pattern 3–8 dB worse than controls at 6 kHz by age 40. Reduce headphone volume and use hearing protection in loud environments to prevent progression.")
                .font(.caption).foregroundStyle(.secondary)
        }
        .padding()
        .background(Color.orange.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .padding(.horizontal)
    }

    // MARK: - History Card

    private var historyCard: some View {
        VStack(alignment: .leading, spacing: 10) {
            Label("Audiogram History", systemImage: "list.bullet.clipboard")
                .font(.subheadline).bold()

            ForEach(audiograms.reversed()) { a in
                HStack {
                    Image(systemName: a.hearingClass == .normal ? "checkmark.circle.fill" : "exclamationmark.circle")
                        .foregroundStyle(a.hearingClass.color)
                    VStack(alignment: .leading, spacing: 2) {
                        Text(a.label).font(.caption.bold())
                        Text(a.hearingClass.rawValue).font(.caption2).foregroundStyle(a.hearingClass.color)
                    }
                    Spacer()
                    Text(String(format: "%.0f dBHL worst", a.worstThreshold))
                        .font(.caption).foregroundStyle(.secondary)
                }
                .padding(.vertical, 2)
                if a.id != audiograms.reversed().last?.id {
                    Divider()
                }
            }
        }
        .padding()
        .background(Color(.secondarySystemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .padding(.horizontal)
    }

    // MARK: - Science Card

    private var scienceCard: some View {
        VStack(alignment: .leading, spacing: 8) {
            Label("Audiogram Science", systemImage: "books.vertical")
                .font(.subheadline).bold()
            Text("An audiogram measures the softest sound detectable at each frequency. Noise-induced hearing loss first appears at 4–6 kHz — above the speech range — so it's often unnoticed until it has spread to speech frequencies (250 Hz–3 kHz).")
                .font(.caption).foregroundStyle(.secondary)
            Text("WHO 2021 (World Hearing Report): 430 million people globally need rehabilitation for disabling hearing loss. Noise exposure is preventable — each 3 dB increase in exposure halves the safe duration (NIOSH exchange rate). Hearing protection at >85 dB prevents the majority of occupational hearing loss.")
                .font(.caption).foregroundStyle(.secondary)
            Text("iPhone's Hearing Test (iOS 18+, AirPods Pro 2) generates audiogram data stored in HealthKit. Regular retesting tracks progression and alerts you to changes before hearing loss becomes disabling.")
                .font(.caption2).foregroundStyle(.tertiary)
        }
        .padding()
        .background(Color.purple.opacity(0.06))
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .padding(.horizontal)
    }

    // MARK: - No Data

    private var noDataCard: some View {
        VStack(spacing: 12) {
            Image(systemName: "ear.fill")
                .font(.largeTitle).foregroundStyle(.secondary)
            Text("No audiogram data")
                .font(.headline)
            Text("Audiogram data comes from iPhone's Hearing Test feature (iOS 18+, requires AirPods Pro 2 or compatible headphones) or clinical audiogram records imported to Health app.")
                .font(.subheadline).foregroundStyle(.secondary)
                .multilineTextAlignment(.center).padding(.horizontal)
        }
        .padding(40)
    }

    // MARK: - Helpers

    private func statBox(value: String, label: String, sub: String, color: Color) -> some View {
        VStack(spacing: 2) {
            Text(value).font(.title3.weight(.bold)).foregroundStyle(color)
            Text(label).font(.caption2).foregroundStyle(.secondary)
            Text(sub).font(.caption2).foregroundStyle(.tertiary)
        }
        .frame(maxWidth: .infinity)
    }

    // MARK: - Data Loading

    private func loadData() async {
        guard HKHealthStore.isHealthDataAvailable() else { isLoading = false; return }

        let audiogramType = HKObjectType.audiogramSampleType()
        guard (try? await healthStore.requestAuthorization(toShare: [], read: [audiogramType])) != nil else {
            isLoading = false; return
        }

        var rawSamples: [HKAudiogramSample] = []
        await withCheckedContinuation { cont in
            let q = HKSampleQuery(sampleType: audiogramType, predicate: nil,
                                  limit: HKObjectQueryNoLimit,
                                  sortDescriptors: [NSSortDescriptor(key: HKSampleSortIdentifierStartDate, ascending: true)]) { _, s, _ in
                rawSamples = (s as? [HKAudiogramSample]) ?? []
                cont.resume()
            }
            healthStore.execute(q)
        }

        let fmt = DateFormatter(); fmt.dateStyle = .medium; fmt.timeStyle = .none
        let dBHL = HKUnit.decibelHearingLevel()
        let hz   = HKUnit.hertz()

        let audiograms: [Audiogram] = rawSamples.map { sample in
            let points = sample.sensitivityPoints.map { p -> Audiogram.FreqPoint in
                let freq  = p.frequency.doubleValue(for: hz)
                let left  = p.leftEarSensitivity?.doubleValue(for: dBHL)
                let right = p.rightEarSensitivity?.doubleValue(for: dBHL)
                return Audiogram.FreqPoint(freqHz: freq, leftDBHL: left, rightDBHL: right)
            }
            return Audiogram(date: sample.startDate, label: fmt.string(from: sample.startDate), points: points)
        }

        DispatchQueue.main.async {
            self.audiograms = audiograms
            self.isLoading  = false
        }
    }
}
