import SwiftUI

// MARK: - WorkoutAnalyticsView

/// Hub view listing all workout analysis sections and cross-cutting analytics.
struct WorkoutAnalyticsView: View {

    private struct AnalyticsEntry: Identifiable {
        let id = UUID()
        let title: String
        let subtitle: String
        let icon: String
        let color: Color
        let destination: AnyView
    }

    private let sections: [(header: String, entries: [AnalyticsEntry])] = [
        (
            header: "Sport Analysis",
            entries: [
                AnalyticsEntry(title: "Walking Science", subtitle: "Step count health outcomes, gait biomechanics, cognitive benefits & optimal protocols — Paluch 2021 JAMA, Studenski 2011 JAMA", icon: "figure.walk.circle.fill", color: .green,
                               destination: AnyView(WalkingScienceView())),
                AnalyticsEntry(title: "Walking", subtitle: "Pace, distance & weekly volume", icon: "figure.walk", color: .green,
                               destination: AnyView(WalkingAnalysisView())),
                AnalyticsEntry(title: "Walking Patterns", subtitle: "DOW distribution, time-of-day & monthly distance trend", icon: "chart.bar.xaxis", color: .green,
                               destination: AnyView(WalkingPatternView())),
                AnalyticsEntry(title: "Walking Progression", subtitle: "12-month distance & pace trend with quarterly breakdown", icon: "chart.line.uptrend.xyaxis", color: .green,
                               destination: AnyView(WalkingProgressionView())),
                AnalyticsEntry(title: "Yoga Science", subtitle: "Flexibility, pranayama & HRV, mental health neuroscience & strength — Cramer 2013: yoga reduces chronic LBP 48%; Streeter 2010: 27% GABA increase", icon: "figure.mind.and.body.fill", color: .purple,
                               destination: AnyView(YogaScienceView())),
                AnalyticsEntry(title: "Yoga & Mind-Body", subtitle: "Session frequency, duration & practice type breakdown", icon: "figure.mind.and.body", color: .purple,
                               destination: AnyView(YogaAnalysisView())),
                AnalyticsEntry(title: "Pilates Science", subtitle: "Core anatomy, back rehabilitation, neuromotor control & Pilates vs yoga — Wells 2014: LBP −36%; Hodges 1996: multifidus as lumbar stabilizer", icon: "figure.pilates", color: .pink,
                               destination: AnyView(PilatesScienceView())),
                AnalyticsEntry(title: "Pilates & Barre", subtitle: "Pilates, barre, flexibility & core training — type mix & duration", icon: "figure.pilates", color: .purple,
                               destination: AnyView(PilatesBarreView())),
                AnalyticsEntry(title: "Mental Health Science", subtitle: "Exercise & depression, cognitive health & mindfulness — Blumenthal 1999: exercise = sertraline efficacy; Erickson 2011: +2% hippocampal volume; Hofmann 2010: MBSR reduces anxiety d=0.97; Davidson 2003: meditation +30% antibody titers", icon: "brain.filled.head.profile", color: .purple,
                               destination: AnyView(MentalHealthScienceView())),
                AnalyticsEntry(title: "Mindful Minutes", subtitle: "Meditation streaks, session trends & time-of-day practice pattern", icon: "brain.head.profile", color: .purple,
                               destination: AnyView(MindfulMinutesView())),
                AnalyticsEntry(title: "Stair Climbing Science", subtitle: "Cardiovascular demand, muscle biomechanics, longevity research & protocols — Ekelund 2019 BMJ: 4 flights/day = 17% lower CVD mortality", icon: "figure.stair.stepper", color: .orange,
                               destination: AnyView(StairClimbingScienceView())),
                AnalyticsEntry(title: "Stair Climbing", subtitle: "Session trends, kcal/min intensity & weekly volume", icon: "figure.stair.stepper", color: .orange,
                               destination: AnyView(StairClimbingView())),
                AnalyticsEntry(title: "Elliptical Science", subtitle: "Cardiovascular physiology, joint biomechanics & rehab — Porcari 1998: elliptical at matched RPE = identical VO₂ to treadmill with 45% less knee loading", icon: "figure.elliptical", color: .cyan,
                               destination: AnyView(EllipticalScienceView())),
                AnalyticsEntry(title: "Elliptical", subtitle: "Session volume, calorie intensity & duration trend", icon: "figure.elliptical", color: .cyan,
                               destination: AnyView(EllipticalAnalysisView())),
                AnalyticsEntry(title: "Golf Science", subtitle: "Swing biomechanics, walking load & mental performance — Hume 2005: X-factor 45–55° drives clubhead speed 160–180 km/h; Murray 2017: 18 holes = 8–12 km; Farahmand 2009: golfers live 5 years longer; McHardy 2007: LBP = 35% of all injuries", icon: "figure.golf", color: .green,
                               destination: AnyView(GolfScienceView())),
                AnalyticsEntry(title: "Golf", subtitle: "Distance walked, calories & monthly round frequency", icon: "figure.golf", color: .green,
                               destination: AnyView(GolfAnalysisView())),
                AnalyticsEntry(title: "Soccer", subtitle: "Match distance, calorie intensity & monthly session frequency", icon: "soccerball", color: .green,
                               destination: AnyView(SoccerAnalysisView())),
                AnalyticsEntry(title: "Soccer Science Deep Dive", subtitle: "GPS demands, positional profiles & heading brain health — Bradley 2009: 30–60 sprints/game; Di Salvo 2007: box-to-box midfielders 12.8 km/game; Lipton 2013: >1,000 headers/year linked to impaired memory", icon: "soccerball.inverse", color: .green,
                               destination: AnyView(SoccerScienceView())),
                AnalyticsEntry(title: "Basketball Science", subtitle: "Jump mechanics, shooting biomechanics & position-specific demands — McInnes 1995: guards 4.8 km/game; Ziv & Lidor 2010: NBA SF avg 67 cm vertical; Okazaki 2006: optimal shot arc 45–55°; Cheng 2016: fatigue reduces 3-point accuracy 3.5% in OT", icon: "basketball.fill", color: .orange,
                               destination: AnyView(BasketballScienceView())),
                AnalyticsEntry(title: "Basketball", subtitle: "Session history, calorie burn & weekly volume", icon: "basketball.fill", color: .orange,
                               destination: AnyView(BasketballAnalysisView())),
                AnalyticsEntry(title: "Dance Science", subtitle: "Movement biomechanics, metabolic demands & brain health — Verghese 2003: dancing reduces dementia risk 76%; Wyon 2004: dancers VO₂max 48–54; Bronner 2006: 1.24 injuries/1,000h; Rodrigues-Krause 2015: Zumba 6.1–8.5 METs", icon: "music.note", color: .pink,
                               destination: AnyView(DanceScienceView())),
                AnalyticsEntry(title: "Dance & Aerobics", subtitle: "Dance, social dance & step training sessions — frequency & calorie trends", icon: "music.note", color: .pink,
                               destination: AnyView(DanceAnalysisView())),
                AnalyticsEntry(title: "Racquet Sports", subtitle: "Pickleball, badminton, racquetball & squash — sport mix & session history", icon: "figure.badminton", color: .green,
                               destination: AnyView(RacquetSportsView())),
                AnalyticsEntry(title: "Martial Arts & Combat", subtitle: "Kickboxing, boxing, martial arts & wrestling — intensity & weekly volume", icon: "figure.kickboxing", color: .red,
                               destination: AnyView(MartialArtsView())),
                AnalyticsEntry(title: "Boxing", subtitle: "Punch biomechanics, round energy systems & brain health — Turner 2011: elite boxers generate 2.4–4.8 kN; Dunn 2016: avg 175–185 bpm per round; Davis 2002: PCr+glycolytic = 90% of early-round energy", icon: "figure.boxing", color: .red,
                               destination: AnyView(BoxingView())),
                AnalyticsEntry(title: "Wrestling", subtitle: "Takedown mechanics, mat conditioning & weight management — Yoon 2002: match HR 175–190 bpm; blood lactate 8–14 mmol/L; Fogelholm 1994: 5% BW dehydration reduces anaerobic power 9.5%; cauliflower ear prevention", icon: "figure.wrestling", color: .indigo,
                               destination: AnyView(WrestlingView())),
                AnalyticsEntry(title: "Jump Rope Science", subtitle: "Metabolic demand, neuromotor coordination & athlete applications — Baker 1999: 120 RPM = 11–12 METs (running 8 mph); Ozer 2011: 22–30% coordination improvement vs running", icon: "figure.jumprope", color: .cyan,
                               destination: AnyView(JumpRopeScienceView())),
                AnalyticsEntry(title: "Jump Rope", subtitle: "Skipping sessions, kcal/min intensity & weekly volume", icon: "figure.jumprope", color: .cyan,
                               destination: AnyView(JumpRopeView())),
                AnalyticsEntry(title: "Winter Sports", subtitle: "Skiing, snowboarding, cross-country & ice skating — seasonal sport history", icon: "snowflake", color: .blue,
                               destination: AnyView(WinterSportsView())),
                AnalyticsEntry(title: "Cross-Country Skiing", subtitle: "World's highest VO₂max sport — Ingjer 1991: Dæhlie 96 mL/kg/min; Seiler 2009: 80/20 polarization; Holmberg 2005: double-poling 500–700 W; Stray-Gundersen 1992: live-high-train-low boosts hemoglobin 5%", icon: "figure.skiing.crosscountry", color: .cyan,
                               destination: AnyView(CrossCountrySkiingView())),
                AnalyticsEntry(title: "Water & Paddle Sports", subtitle: "Surfing, paddleboarding, kayaking & water fitness — sessions & sport mix", icon: "figure.surfing", color: .blue,
                               destination: AnyView(WaterSportsView())),
                AnalyticsEntry(title: "Surfing Deep Dive", subtitle: "Paddle mechanics, pop-up biomechanics & surf fitness — Farley 2012: paddling = 54% of session; Nathanson 2002: board impact = 55% of injuries; Rinaldi 2014: exostosis risk in cold water", icon: "wave.3.forward", color: .cyan,
                               destination: AnyView(SurfingView())),
                AnalyticsEntry(title: "Diving Analytics", subtitle: "Underwater depth, water temperature & no-deco limits — Apple Watch Ultra", icon: "water.waves", color: .cyan,
                               destination: AnyView(DivingAnalyticsView())),
                AnalyticsEntry(title: "Triathlon", subtitle: "Swim/bike/run volume split, brick workout detection & race-type distribution target", icon: "sportscourt.fill", color: .blue,
                               destination: AnyView(TriathlonView())),
                AnalyticsEntry(title: "Open Water Swimming", subtitle: "OWS pace per 100m, distance trend & monthly volume", icon: "figure.pool.swim", color: .cyan,
                               destination: AnyView(OpenWaterSwimmingView())),
                AnalyticsEntry(title: "Functional Strength", subtitle: "CrossFit, calisthenics & Olympic lifting — intensity & weekly volume", icon: "figure.strengthtraining.functional", color: .orange,
                               destination: AnyView(FunctionalStrengthView())),
                AnalyticsEntry(title: "Rock Climbing Science", subtitle: "Finger physiology, movement biomechanics & injury prevention — Schweizer 2001: A2 pulley force 380–420 N in crimping; MacLeod 2007: elite flexor CSA 40% larger; Pieber 2012: 4.2 injuries/1,000h; España-Romero 2009: forearm VO₂peak 4× resting", icon: "figure.climbing", color: .brown,
                               destination: AnyView(RockClimbingScienceView())),
                AnalyticsEntry(title: "Rock Climbing", subtitle: "Session duration, calorie intensity & weekly climbing volume", icon: "figure.climbing", color: .brown,
                               destination: AnyView(RockClimbingView())),
                AnalyticsEntry(title: "Volleyball Science", subtitle: "Jump biomechanics, energy systems & beach vs indoor science — Marques 2009: elite jump 80–90 cm; Forthomme 2005: spike IR velocity 4,500–5,000°/s; Lian 2005: patellar tendinopathy in 45% of elite players; Giatsis 2011: beach VB burns 30–40% more kcal/min", icon: "volleyball.fill", color: .yellow,
                               destination: AnyView(VolleyballScienceView())),
                AnalyticsEntry(title: "Volleyball", subtitle: "Session frequency, calorie burn & heart rate intensity", icon: "volleyball.fill", color: .yellow,
                               destination: AnyView(VolleyballAnalysisView())),
                AnalyticsEntry(title: "Baseball & Softball", subtitle: "Game sessions, intermittent burst intensity & arm load — Escamilla & Andrews 2009 throwing biomechanics", icon: "figure.baseball", color: .blue,
                               destination: AnyView(BaseballSoftballView())),
                AnalyticsEntry(title: "Rugby & Football", subtitle: "Match load, recovery gap & collision intensity — Cunniffe 2009: 35–40% match time >85% HRmax, Twist 2012: 72–96h muscle recovery", icon: "sportscourt.fill", color: .green,
                               destination: AnyView(RugbyAnalysisView())),
                AnalyticsEntry(title: "American Football", subtitle: "Positional demands, concussion science & explosive performance — Brechue 2010: NFL Combine data by position; McKee 2023: CTE in 110/111 donated NFL brains; Mihalik 2011: neck strength reduces angular acceleration 20–33%", icon: "football.fill", color: .brown,
                               destination: AnyView(AmericanFootballView())),
                AnalyticsEntry(title: "Australian Football (AFL)", subtitle: "World's most demanding team sport — Coutts 2010: midfielders run 16–18 km/game; Gastin 2013: 88–90% aerobic; Ball 2008: punt kick hip rotation 570–620°/s; Orchard 2013: hamstring = most common injury 7.4/club/season", icon: "soccerball.inverse", color: .red,
                               destination: AnyView(AustralianFootballView())),
                AnalyticsEntry(title: "Hockey & Lacrosse", subtitle: "Ice hockey, field hockey & lacrosse game load — Quinney 2008: 170–185 bpm during shifts, Spencer 2005: 9–12 km per field hockey game", icon: "figure.hockey", color: .cyan,
                               destination: AnyView(HockeyAnalysisView())),
                AnalyticsEntry(title: "Lacrosse", subtitle: "Shot physics, cradling centripetal mechanics & game load — Kelly 2012: 5.5–7.5 km/game; Goss 2013: MLL shot 130–160 km/h; Barber 2017: shoulder = 26% of injuries; box vs. field lacrosse intensity differences", icon: "figure.lacrosse", color: .purple,
                               destination: AnyView(LacrosseView())),
                AnalyticsEntry(title: "Track & Field", subtitle: "Sprint vs. distance breakdown, energy systems & VO₂max — Haugen 2019: elite 100m ground contact ≤80 ms, Jones & Carter 2000: energy system split by event", icon: "figure.run.circle", color: .orange,
                               destination: AnyView(TrackAndFieldView())),
                AnalyticsEntry(title: "Fitness Gaming", subtitle: "Exergaming: Ring Fit, Beat Saber, VR fitness — Peng 2011: 2–3× resting expenditure; Staiano 2011: 30–50% lower dropout vs. traditional exercise", icon: "gamecontroller.fill", color: .purple,
                               destination: AnyView(FitnessGamingView())),
                AnalyticsEntry(title: "Disc Sports", subtitle: "Ultimate frisbee, disc golf & freestyle — Duthie 2003: 8–12 km per ultimate game, 30% sprint; Levy & Sherrin 2008: disc golf ≈ 4.1 METs", icon: "figure.disc.sports", color: .green,
                               destination: AnyView(DiscSportsView())),
                AnalyticsEntry(title: "Wheelchair Fitness", subtitle: "Push load, intensity & shoulder health — de Groot 2008: wheeling exercise cardioprotective for SCI; van der Woude 2006: long strokes reduce shoulder forces 30–40%", icon: "figure.roll", color: .blue,
                               destination: AnyView(WheelchairFitnessView())),
                AnalyticsEntry(title: "Handcycling", subtitle: "Upper-body aerobic zones & efficiency — Hettinga 2010: recumbent handcycling achieves 85–95% of upright cycling VO₂; Fischer 2014: 12-week training → VO₂peak +16%", icon: "figure.hand.cycling", color: .cyan,
                               destination: AnyView(HandcyclingView())),
                AnalyticsEntry(title: "Fencing", subtitle: "Explosive bout analysis, tournament load & weapon demands — Turner 2014: 30–50 actions/bout at 80–85% HRmax; Roi 2008: lunge = 2× bodyweight GRF in 0.5–1.5 s", icon: "figure.fencing", color: .red,
                               destination: AnyView(FencingView())),
                AnalyticsEntry(title: "Gymnastics", subtitle: "Strength standards, injury prevention & energy systems — Prassas 2006: floor 80% anaerobic; Naughton 2000: gymnastics increases BMD 10–30% above controls", icon: "figure.gymnastics", color: .purple,
                               destination: AnyView(GymnasticsView())),
                AnalyticsEntry(title: "Badminton", subtitle: "World's fastest racquet sport — Phomsoupha 2015: shuttle 493 km/h; Gawin 2015: 1300–2000 direction changes/match; Liddle 1996: 85–90% HRmax average", icon: "figure.badminton", color: .red,
                               destination: AnyView(BadmintonView())),
                AnalyticsEntry(title: "Handball", subtitle: "Match load, throwing biomechanics & jump performance — Michalsik 2013: 4–6 km at high intensity/game; Wagner 2011: 80–120 km/h throwing velocity", icon: "figure.handball", color: .blue,
                               destination: AnyView(HandballView())),
                AnalyticsEntry(title: "Curling", subtitle: "Sweeping load, position-based kcal & delivery mechanics — Lanovaz 2001: sweepers reach 75–85% HRmax; Headrick 2007: lead position 600–800 kcal/game", icon: "figure.curling", color: .cyan,
                               destination: AnyView(CurlingView())),
                AnalyticsEntry(title: "Step Aerobics", subtitle: "Intensity zones by kcal/min & VO₂max gains — Olson 1996: 8\" step = 65–75% VO₂max ≈ running 5–6 mph; Macfarlane 2012: +9% VO₂max in 8 weeks; Lossing 1997: 1.5–1.8× BW tibial force (vs 2–3× running)", icon: "figure.step.training", color: .orange,
                               destination: AnyView(StepAerobicsView())),
                AnalyticsEntry(title: "Table Tennis", subtitle: "Match intensity, rally physics & reaction time — Zagatto 2010: match VO₂ 45–65% with bursts to 85%; Yuza 1992: elite reaction time 250–300 ms — 25% faster than untrained", icon: "figure.table.tennis", color: .blue,
                               destination: AnyView(TableTennisView())),
                AnalyticsEntry(title: "Cricket", subtitle: "Bowling workload, fielding intensity & batting demand — Petersen 2010: fast bowlers produce 6–9× BW GRF; Duffield 2008: T20 fielding averages 80–85% HRmax", icon: "figure.cricket", color: .green,
                               destination: AnyView(CricketView())),
                AnalyticsEntry(title: "Water Polo", subtitle: "Eggbeater kick energy cost, explosive jump height & match intensity — Smith 1998: 48% of match at >80% HRmax; eggbeater = 35–50% of total match kcal", icon: "figure.water.fitness", color: .cyan,
                               destination: AnyView(WaterPoloView())),
                AnalyticsEntry(title: "Squash", subtitle: "The most aerobically intense racquet sport — Todd 1998: 85–95% HRmax sustained; Wilkinson 2009: lactate 6–10 mmol/L; Novas 2003: 18 direction changes/min in 9.75×6.4 m court", icon: "figure.squash", color: .red,
                               destination: AnyView(SquashView())),
                AnalyticsEntry(title: "Archery", subtitle: "Cardiac timing, shoulder isometric load & breath control — Shing 2015: elite archers time release to cardiac diastole; Clarys 1990: posterior deltoid at 65–80% MVC per draw", icon: "figure.archery", color: .indigo,
                               destination: AnyView(ArcheryView())),
                AnalyticsEntry(title: "Tai Chi", subtitle: "Balance, blood pressure & neurological benefits — Wolf 1996: 47.5% fall risk reduction; Yeh 2011: −15.6 mmHg SBP; Li 2012 (NEJM): superior to resistance training for Parkinson's balance", icon: "figure.taichi", color: .teal,
                               destination: AnyView(TaiChiView())),
                AnalyticsEntry(title: "Core Training", subtitle: "McGill Big 3, inner/outer unit anatomy & frequency science — Reed 2012: targeted core work reduces chronic LBP 35%; Stokes 2010: +4.6% running performance in 6 weeks", icon: "figure.core.training", color: .blue,
                               destination: AnyView(CoreTrainingView())),
                AnalyticsEntry(title: "Flexibility", subtitle: "Myth-busting stretching science — Harvey 2002: stretching does NOT prevent injury; Simic 2013: pre-exercise static stretch impairs strength −5.5%; what actually works for ROM", icon: "figure.flexibility", color: .purple,
                               destination: AnyView(FlexibilityView())),
                AnalyticsEntry(title: "Prep & Recovery", subtitle: "Warm-up science, PAP & recovery modalities — Fradkin 2010: warm-up improves performance in 79% of studies (+4.7%); McGowan 2015: PAP adds +5–12% power; ice bath trade-offs", icon: "arrow.clockwise.heart", color: .green,
                               destination: AnyView(PrepRecoveryView())),
                AnalyticsEntry(title: "Sailing", subtitle: "Dinghy hiking isometric demands & offshore physiology — Blackburn 1994: 60–80% MVC quad sustained 20+ min; Callewaert 2012: quad endurance (not cardio) limits performance", icon: "sailboat", color: .cyan,
                               destination: AnyView(SailingView())),
                AnalyticsEntry(title: "Pickleball", subtitle: "America's fastest-growing sport — Decker 2023: averages 75–85% HRmax (vigorous intensity); Doose 2021: depression −11.7%; Casper 2021: 73% 12-month retention", icon: "figure.pickleball", color: .green,
                               destination: AnyView(PickleballView())),
                AnalyticsEntry(title: "Bowling", subtitle: "67M US participants — Stuelcken 2005: wrist 700–900°/s at release; Lam 2013: 200–500 RPM rev rate; Piasecki 2018: 30–45% medial epicondylitis at >70 games/week; Dorsel 2001: spare conversion predicts score", icon: "figure.bowling", color: .blue,
                               destination: AnyView(BowlingView())),
                AnalyticsEntry(title: "Skateboarding", subtitle: "Ollie biomechanics, balance adaptation & injury prevention — Roces 2001: pop generates 3–5× BW GRF; Rinaldi 2014: skaters show 30% smaller balance sway; Schieber 1996: wrist guards reduce fracture risk 85%", icon: "figure.skateboarding", color: .orange,
                               destination: AnyView(SkateboardingView())),
                AnalyticsEntry(title: "Equestrian Sports", subtitle: "Horseback riding, dressage & trail sessions — duration & monthly history", icon: "figure.equestrian.sports", color: .brown,
                               destination: AnyView(EquestrianView())),
                AnalyticsEntry(title: "Cross-Training Science", subtitle: "CrossFit physiology, metabolic conditioning & recovery — Smith 2013: Fran reaches 98% HRmax; Tabata 1996: +14% VO₂max +28% anaerobic in 6 weeks; Hak 2013: 3.1 injuries/1,000h; Boutcher 2011: HIIT reduces visceral fat 17%", icon: "figure.cross.training", color: .red,
                               destination: AnyView(CrossTrainingScienceView())),
                AnalyticsEntry(title: "Cross-Training", subtitle: "CrossFit & mixed cardio sessions, intensity & weekly volume", icon: "figure.cross.training", color: .red,
                               destination: AnyView(CrossTrainingView())),
                AnalyticsEntry(title: "Tennis Science", subtitle: "Serve biomechanics, movement science & energy systems — Roetert 1995: elite serves 180–200 km/h; Kovacs 2006: 300–500 direction changes/match; Abrams 2012: tennis elbow in 40–50% recreational players; Girard 2011: jump height drops 5.3% in five-set matches", icon: "figure.tennis", color: .yellow,
                               destination: AnyView(TennisScienceView())),
                AnalyticsEntry(title: "Tennis", subtitle: "Session history, calories & monthly match frequency", icon: "figure.tennis", color: .yellow,
                               destination: AnyView(TennisAnalysisView())),
                AnalyticsEntry(title: "Outdoor vs Indoor", subtitle: "Environment split by sport, monthly trend & preference", icon: "sun.and.horizon.fill", color: .yellow,
                               destination: AnyView(OutdoorIndoorView())),
                AnalyticsEntry(title: "Running Cadence", subtitle: "Steps per minute trend, optimal 165–175 spm target — Heiderscheit 2011 injury prevention science", icon: "figure.run.motion", color: .orange,
                               destination: AnyView(RunningCadenceView())),
                AnalyticsEntry(title: "Running Biomechanics", subtitle: "Ground contact time, vertical oscillation & stride length — Morin 2011, Tartaruga 2012 (Apple Watch Ultra / S8+, iOS 16+)", icon: "figure.run.square.stack.fill", color: .purple,
                               destination: AnyView(RunningBiomechanicsView())),
                AnalyticsEntry(title: "Running Science", subtitle: "Biomechanics, VO₂max adaptations, race physiology & injury prevention — Saunders 2004, Seiler 2010, Heiderscheit 2011", icon: "figure.run.circle.fill", color: .orange,
                               destination: AnyView(RunningScienceView())),
                AnalyticsEntry(title: "Running", subtitle: "Pace, distance & PRs", icon: "figure.run", color: .orange,
                               destination: AnyView(RunningAnalysisView())),
                AnalyticsEntry(title: "Running Patterns", subtitle: "DOW distribution, time-of-day & pace trend", icon: "chart.bar.xaxis", color: .green,
                               destination: AnyView(RunningPatternView())),
                AnalyticsEntry(title: "Cycling Science", subtitle: "Power & FTP, pedaling biomechanics & physiology — Allen 2010: FTP = 95% of 20-min max; Bassett 2000: elite VO₂max 75–90 mL/kg/min; Leirdal 2011: 90 RPM cuts type II fiber use 18%; Bini 2014: 85% of cyclists sustain season injury", icon: "figure.outdoor.cycle", color: .blue,
                               destination: AnyView(CyclingScienceView())),
                AnalyticsEntry(title: "Cycling", subtitle: "Speed, distance & weekly volume", icon: "figure.outdoor.cycle", color: .blue,
                               destination: AnyView(CyclingAnalysisView())),
                AnalyticsEntry(title: "Cycling Patterns", subtitle: "DOW distribution, time-of-day & speed trend", icon: "chart.bar.xaxis", color: .blue,
                               destination: AnyView(CyclingPatternView())),
                AnalyticsEntry(title: "Cycling Progression", subtitle: "12-month distance & speed trend with elevation", icon: "chart.line.uptrend.xyaxis", color: .blue,
                               destination: AnyView(CyclingProgressionView())),
                AnalyticsEntry(title: "Cycling Cadence", subtitle: "RPM trend, zone distribution & optimal 85–100 RPM target — Apple Watch Ultra", icon: "speedometer", color: .green,
                               destination: AnyView(CyclingCadenceView())),
                AnalyticsEntry(title: "Power-to-Weight", subtitle: "FTP W/kg ratio, British Cycling tier & weight impact simulator (iOS 17+)", icon: "bolt.fill", color: .yellow,
                               destination: AnyView(PowerToWeightView())),
                AnalyticsEntry(title: "Cycling Speed", subtitle: "Session avg & max speed, zone distribution & 90-day trend (iOS 17+)", icon: "gauge.with.needle.fill", color: .teal,
                               destination: AnyView(CyclingSpeedView())),
                AnalyticsEntry(title: "Cycling Power", subtitle: "FTP, power zones (Z1–Z7), power curve & TSS — compatible power meters", icon: "bolt.circle.fill", color: .yellow,
                               destination: AnyView(CyclingPowerView())),
                AnalyticsEntry(title: "Swimming Science", subtitle: "Stroke biomechanics, hydrodynamics & physiology — Toussaint 1988: elite propulsive force 60–80 N; Pendergast 1977: active drag 5–10× passive; Holmér 1974: elite VO₂max 65–75 mL/kg/min; Mujika 1995: 2–3 week taper adds 1–3% race velocity", icon: "figure.pool.swim", color: .cyan,
                               destination: AnyView(SwimmingScienceView())),
                AnalyticsEntry(title: "Swimming", subtitle: "Pace per 100m & pool sets", icon: "figure.pool.swim", color: .cyan,
                               destination: AnyView(SwimmingAnalysisView())),
                AnalyticsEntry(title: "Swimming Patterns", subtitle: "DOW distribution, time-of-day & pace per 100m trend", icon: "chart.bar.xaxis", color: .cyan,
                               destination: AnyView(SwimmingPatternView())),
                AnalyticsEntry(title: "Swimming Progression", subtitle: "12-month distance & pace per 100m trend", icon: "chart.line.uptrend.xyaxis", color: .cyan,
                               destination: AnyView(SwimmingProgressionView())),
                AnalyticsEntry(title: "Stroke Efficiency", subtitle: "SWOLF score, distance-per-stroke & stroke rate — pool swim analytics", icon: "figure.pool.swim", color: .teal,
                               destination: AnyView(SwimmingStrokeEfficiencyView())),
                AnalyticsEntry(title: "Rowing Stroke Rate", subtitle: "SPM trend, zone distribution (steady–sprint) & power science", icon: "oar.2.crossed", color: .blue,
                               destination: AnyView(RowingStrokeRateView())),
                AnalyticsEntry(title: "Strength Training Science", subtitle: "Hypertrophy mechanisms, neural adaptations & periodization — Schoenfeld 2010: 3 mechanisms; Morton 2016: 30–80% 1RM all work; Krieger 2010: 10–20 sets/muscle optimal; Rhea 2003: DUP +29% vs linear +14%", icon: "figure.strengthtraining.traditional", color: .red,
                               destination: AnyView(StrengthScienceView())),
                AnalyticsEntry(title: "Strength Training", subtitle: "Frequency, volume & sessions", icon: "figure.strengthtraining.traditional", color: .red,
                               destination: AnyView(StrengthAnalysisView())),
                AnalyticsEntry(title: "Strength Patterns", subtitle: "DOW distribution, time-of-day & duration trend", icon: "chart.bar.xaxis", color: .red,
                               destination: AnyView(StrengthPatternView())),
                AnalyticsEntry(title: "Strength Progression", subtitle: "12-month volume trend, duration trend & quarterly breakdown", icon: "chart.line.uptrend.xyaxis", color: .red,
                               destination: AnyView(StrengthProgressionView())),
                AnalyticsEntry(title: "Hiking Science", subtitle: "Terrain physiology, elevation biomechanics & nature neuroscience — Bratman 2015 PNAS: 90-min hike reduces sgPFC activity; Stamatakis 2018: hill hiking = 38% lower all-cause mortality", icon: "mountain.2", color: .green,
                               destination: AnyView(HikingScienceView())),
                AnalyticsEntry(title: "Hiking", subtitle: "Distance, elevation & hike log", icon: "figure.hiking", color: .green,
                               destination: AnyView(HikingAnalysisView())),
                AnalyticsEntry(title: "Hiking Patterns", subtitle: "DOW distribution, time-of-day & elevation trend", icon: "chart.bar.xaxis", color: .green,
                               destination: AnyView(HikingPatternView())),
                AnalyticsEntry(title: "Hiking Progression", subtitle: "12-month distance & elevation gain trend", icon: "chart.line.uptrend.xyaxis", color: .green,
                               destination: AnyView(HikingProgressionView())),
                AnalyticsEntry(title: "Elevation Analysis", subtitle: "GPS route elevation gain from runs & hikes — Minetti 2002: +6% grade costs 2× flat energy, Gimenez 2013: hilly runs cause 2–3× more muscle damage", icon: "mountain.2.fill", color: .orange,
                               destination: AnyView(ElevationAnalysisView())),
                AnalyticsEntry(title: "HIIT Science", subtitle: "Intervals, physiology & protocols — Tabata 1996: 4 min = +14% VO₂max +28% anaerobic; Wisløff 2007: 4×4 = +46% VO₂max post-MI; Boutcher 2011: HIIT reduces visceral fat 17%; Buchheit 2013: 90–95% HRmax is the sweet spot", icon: "bolt.heart.fill", color: .pink,
                               destination: AnyView(HIITScienceView())),
                AnalyticsEntry(title: "HIIT", subtitle: "Peak HR, burn rate & intensity", icon: "bolt.heart.fill", color: .pink,
                               destination: AnyView(HIITAnalysisView())),
                AnalyticsEntry(title: "HIIT Patterns", subtitle: "DOW distribution, time-of-day & weekly volume", icon: "chart.bar.xaxis", color: .yellow,
                               destination: AnyView(HIITPatternView())),
                AnalyticsEntry(title: "HIIT Progression", subtitle: "12-month frequency, duration trend & calorie burn", icon: "chart.line.uptrend.xyaxis", color: .pink,
                               destination: AnyView(HIITProgressionView())),
                AnalyticsEntry(title: "Rowing Science", subtitle: "Stroke biomechanics, VO₂ demands & ergometer training science — Hagerman 1984: 98–100% VO₂max at race pace; Kleshnev 2016: legs 55–65% of power output; Hosea 1990: 72% of elite rowers report LBP; Steinacker 1993: rowing engages 86% of total muscle mass", icon: "figure.rowing", color: .cyan,
                               destination: AnyView(RowingScienceView())),
                AnalyticsEntry(title: "Rowing", subtitle: "500m splits, distance & HR", icon: "figure.rowing", color: .cyan,
                               destination: AnyView(RowingAnalysisView())),
                AnalyticsEntry(title: "Rowing Patterns", subtitle: "DOW distribution, time-of-day & 500m split trend", icon: "chart.bar.xaxis", color: .pink,
                               destination: AnyView(RowingPatternView())),
                AnalyticsEntry(title: "Rowing Progression", subtitle: "12-month distance & 500m split trend", icon: "chart.line.uptrend.xyaxis", color: .pink,
                               destination: AnyView(RowingProgressionView())),
            ]
        ),
        (
            header: "Training Analytics",
            entries: [
                AnalyticsEntry(title: "Heart Rate Zones", subtitle: "Z1–Z5 distribution across workouts", icon: "heart.circle.fill", color: .red,
                               destination: AnyView(HeartRateZonesView())),
                AnalyticsEntry(title: "Zone Progression", subtitle: "Monthly Z1–Z5 evolution, polarization index & Seiler 80/20 trend", icon: "chart.bar.doc.horizontal", color: .purple,
                               destination: AnyView(HRZoneProgressionView())),
                AnalyticsEntry(title: "Overtraining Science", subtitle: "OTS diagnosis, mechanisms, monitoring & recovery protocols (Meeusen 2013 ECSS/ACSM consensus)", icon: "brain.head.profile", color: .red,
                               destination: AnyView(OvertrainingScienceView())),
                AnalyticsEntry(title: "Overtraining Warning", subtitle: "Composite OTS detector: HRV trend, RHR elevation, ACWR & sleep deficit", icon: "exclamationmark.triangle.fill", color: .red,
                               destination: AnyView(OvertrainingWarningView())),
                AnalyticsEntry(title: "Training Load", subtitle: "Acute:chronic ratio & fatigue", icon: "chart.bar.fill", color: .purple,
                               destination: AnyView(TrainingLoadView())),
                AnalyticsEntry(title: "Running Power", subtitle: "Critical power, power zones (Z1–Z5), NP & trend — Apple Watch Ultra", icon: "bolt.fill", color: .orange,
                               destination: AnyView(RunningPowerZonesView())),
                AnalyticsEntry(title: "Running Form", subtitle: "Cadence, stride & vertical oscillation", icon: "figure.run.motion", color: .orange,
                               destination: AnyView(RunningFormView())),
                AnalyticsEntry(title: "Pacing Analysis", subtitle: "Negative splits, pacing CV & within-run speed variation (iOS 16+)", icon: "gauge.with.dots.needle.67percent", color: .orange,
                               destination: AnyView(RunningPacingView())),
                AnalyticsEntry(title: "Pace Zones", subtitle: "80/20 easy vs hard distribution", icon: "timer", color: .orange,
                               destination: AnyView(RunningPaceZonesView())),
                AnalyticsEntry(title: "Running Efficiency", subtitle: "AEI trend — speed per heartbeat", icon: "gauge.open.with.lines.needle.33percent", color: .green,
                               destination: AnyView(RunningEfficiencyView())),
                AnalyticsEntry(title: "Race Predictor", subtitle: "5K, 10K, half & full via VDOT", icon: "stopwatch.fill", color: .green,
                               destination: AnyView(RacePredictorView())),
                AnalyticsEntry(title: "Race Goal Planner", subtitle: "16-week countdown & progressive mileage plan to target race", icon: "flag.checkered.2.crossed", color: .red,
                               destination: AnyView(RaceGoalPlannerView())),
                AnalyticsEntry(title: "Records & PRs", subtitle: "Your lifetime personal bests", icon: "trophy.fill", color: .yellow,
                               destination: AnyView(RecordsView())),
                AnalyticsEntry(title: "Sleep Impact", subtitle: "How workouts affect overnight HRV & sleep", icon: "bed.double.fill", color: .indigo,
                               destination: AnyView(WorkoutSleepImpactView())),
                AnalyticsEntry(title: "Sleep-Training Balance", subtitle: "Weekly training hours vs sleep hours — Mah 2011 (Sleep): extending sleep 10h improved sprint times 4%", icon: "moon.and.stars.fill", color: .indigo,
                               destination: AnyView(SleepTrainingBalanceView())),
                AnalyticsEntry(title: "Workout Calendar", subtitle: "Monthly view colored by sport type", icon: "calendar.badge.clock", color: .teal,
                               destination: AnyView(WorkoutCalendarView())),
                AnalyticsEntry(title: "Training Advisor", subtitle: "HRV-based weekly training plan", icon: "brain.head.profile", color: .cyan,
                               destination: AnyView(TrainingAdvisorView())),
                AnalyticsEntry(title: "Workout Variety", subtitle: "Sport mix, diversity score & weekly balance", icon: "figure.mixed.cardio", color: .purple,
                               destination: AnyView(WorkoutVarietyView())),
                AnalyticsEntry(title: "Running Progression", subtitle: "12-month pace trend, monthly volume & quarterly breakdown", icon: "chart.line.uptrend.xyaxis", color: .orange,
                               destination: AnyView(RunningProgressionView())),
                AnalyticsEntry(title: "Training Patterns", subtitle: "Day-of-week, time-of-day & weekly volume analysis", icon: "calendar.badge.clock", color: .teal,
                               destination: AnyView(TrainingPatternView())),
                AnalyticsEntry(title: "Workout Efficiency", subtitle: "kcal/min by type — intensity across all sports", icon: "bolt.heart.fill", color: .yellow,
                               destination: AnyView(WorkoutEfficiencyView())),
                AnalyticsEntry(title: "Workout Effort Score", subtitle: "Apple's 1–10 effort rating, session load & 80:20 balance (iOS 17+)", icon: "flame.fill", color: .orange,
                               destination: AnyView(PhysicalEffortView())),
                AnalyticsEntry(title: "Performance Overview", subtitle: "Cross-sport year-over-year comparison", icon: "chart.bar.doc.horizontal.fill", color: .blue,
                               destination: AnyView(PerformanceOverviewView())),
                AnalyticsEntry(title: "Volume History", subtitle: "52-week training breakdown by sport", icon: "chart.bar.fill", color: .orange,
                               destination: AnyView(TrainingVolumeHistoryView())),
                AnalyticsEntry(title: "Zone 2 Training", subtitle: "Aerobic base volume tracker — 52 weeks", icon: "heart.circle.fill", color: .green,
                               destination: AnyView(Zone2TrainingView())),
                AnalyticsEntry(title: "Consistency Tracker", subtitle: "52-week session frequency, streaks & training days", icon: "calendar.badge.checkmark", color: .teal,
                               destination: AnyView(WorkoutConsistencyView())),
                AnalyticsEntry(title: "Lifetime Stats", subtitle: "All-time totals, milestones & year-over-year", icon: "star.circle.fill", color: .teal,
                               destination: AnyView(LifetimeStatsView())),
                AnalyticsEntry(title: "Injury Prevention Science", subtitle: "ACWR, tissue adaptation & overuse injury — Gabbett 2016: ACWR 0.8–1.3 sweet spot; Magnusson 2010: tendons adapt 10× slower than muscle; Hreljac 2004: training errors cause 60–70% of overuse injuries; FIFA 11+ reduces injury 30–50%", icon: "exclamationmark.shield.fill", color: .orange,
                               destination: AnyView(InjuryScienceView())),
                AnalyticsEntry(title: "Injury Risk Score", subtitle: "ACWR, consecutive days, HRV & resting HR risk factors", icon: "exclamationmark.triangle.fill", color: .orange,
                               destination: AnyView(InjuryRiskView())),
                AnalyticsEntry(title: "Fitness Age", subtitle: "VO₂ max-based biological fitness age vs chronological age", icon: "figure.run.circle.fill", color: .indigo,
                               destination: AnyView(FitnessAgeView())),
                AnalyticsEntry(title: "Biological Age", subtitle: "Multi-biomarker age: HRV + RHR + VO₂ + gait speed — Levine 2018 PhenoAge methodology", icon: "dna", color: .teal,
                               destination: AnyView(BiologicalAgeView())),
                AnalyticsEntry(title: "Life Expectancy Impact", subtitle: "Years gained/lost per biomarker — VO₂ + steps + RHR + HRV + sleep vs. population", icon: "hourglass", color: .indigo,
                               destination: AnyView(LifeExpectancyView())),
                AnalyticsEntry(title: "Recovery Optimizer", subtitle: "Per-session next-morning HRV & RHR recovery score by workout type — Buchheit 2014, Plews 2013", icon: "arrow.up.heart.fill", color: .cyan,
                               destination: AnyView(WorkoutRecoveryOptimizerView())),
                AnalyticsEntry(title: "Training Age", subtitle: "Years of consistent training — Bompa 2015 Novice/Intermediate/Advanced/Elite classification", icon: "calendar.badge.plus", color: .purple,
                               destination: AnyView(TrainingAgeView())),
                AnalyticsEntry(title: "Circadian Performance", subtitle: "Peak training time from HR efficiency by time-of-day — Chtourou 2012, Kolbe 2019 circadian biology", icon: "sun.and.horizon.circle.fill", color: .orange,
                               destination: AnyView(CircadianPerformanceView())),
                AnalyticsEntry(title: "Interval Detector", subtitle: "Auto-detects interval structure from HR spread in HIIT & running — Buchheit & Laursen 2013", icon: "waveform.path.ecg.rectangle.fill", color: .orange,
                               destination: AnyView(IntervalDetectorView())),
                AnalyticsEntry(title: "Exercise Snacks", subtitle: "Short ≤15-min workout sessions — Gillen 2016: 3×10 min equals 45 min continuous", icon: "bolt.circle.fill", color: .green,
                               destination: AnyView(ExerciseSnacksView())),
                AnalyticsEntry(title: "Weekly Balance", subtitle: "4-dimension scorecard: cardio + strength + flexibility + recovery — WHO 2020, ACSM 2022", icon: "4.square.fill", color: .teal,
                               destination: AnyView(WeeklyBalanceView())),
                AnalyticsEntry(title: "Training Load (CTL/ATL)", subtitle: "Bannister 1991 fitness-fatigue model: CTL fitness base, ATL fatigue, TSB form — Performance Management Chart", icon: "chart.line.uptrend.xyaxis.circle.fill", color: .blue,
                               destination: AnyView(ChronicTrainingLoadView())),
                AnalyticsEntry(title: "Progressive Overload", subtitle: "Week-over-week volume tracking vs 10% rule — Matveyev 1965, Hreljac 2004 injury risk thresholds", icon: "arrow.up.bar.chart", color: .green,
                               destination: AnyView(ProgressiveOverloadView())),
                AnalyticsEntry(title: "Workload Ratio (ACWR)", subtitle: "Injury risk from load spikes — Gabbett 2016: ACWR > 1.5 = 2-4× injury risk, sweet spot 0.8–1.3", icon: "shield.lefthalf.filled", color: .orange,
                               destination: AnyView(ACWRView())),
                AnalyticsEntry(title: "EPOC — Afterburn Effect", subtitle: "Excess post-exercise O₂ consumption — LaForgia 2006: HIIT produces 6× more afterburn than steady-state", icon: "flame.circle.fill", color: .orange,
                               destination: AnyView(EPOCView())),
                AnalyticsEntry(title: "Glycogen Status", subtitle: "Muscle fuel store estimates from workout energy — Bergström 1967, Burke 2011: replenishment timing & race readiness", icon: "bolt.heart.fill", color: .green,
                               destination: AnyView(GlycogenStatusView())),
                AnalyticsEntry(title: "Cognitive Performance", subtitle: "Daily brain score from sleep + HRV + training load — Killgore 2010, Czeisler 2011 sleep-cognition science", icon: "brain.head.profile", color: .cyan,
                               destination: AnyView(CognitivePerformanceView())),
                AnalyticsEntry(title: "Fiber Type Estimator", subtitle: "Slow vs fast-twitch tendency from workout intensity profile — Costill 1976: elite runners 73% ST, sprinters 24% ST", icon: "figure.strengthtraining.traditional", color: .purple,
                               destination: AnyView(FiberTypeView())),
                AnalyticsEntry(title: "Substrate Metabolism", subtitle: "Fat vs carb oxidation per workout intensity — Brooks 1994 crossover, Achten 2004: peak fat burn at 40–65% VO₂max", icon: "chart.pie.fill", color: .orange,
                               destination: AnyView(SubstrateMetabolismView())),
                AnalyticsEntry(title: "Muscle Recovery Map", subtitle: "Per-muscle recovery status inferred from workout history — Damas 2016 DOMS timeline, Schoenfeld 2010 MPS science", icon: "figure.strengthtraining.traditional", color: .red,
                               destination: AnyView(MuscleRecoveryView())),
                AnalyticsEntry(title: "Training Phases", subtitle: "Auto-detect base, build, peak & taper from 52-week volume", icon: "calendar.badge.clock", color: .blue,
                               destination: AnyView(PeriodizationView())),
                AnalyticsEntry(title: "Monotony & Strain", subtitle: "Coggan's training science — daily load variety & cumulative stress", icon: "waveform.path.ecg", color: .indigo,
                               destination: AnyView(TrainingMonotonyView())),
                AnalyticsEntry(title: "Stress vs Recovery", subtitle: "12-week scatter: training load vs HRV recovery — quadrant analysis", icon: "chart.scatter", color: .purple,
                               destination: AnyView(StressRecoveryView())),
                AnalyticsEntry(title: "ECG History", subtitle: "Sinus rhythm %, AFib burden & classification timeline", icon: "waveform.path.ecg.rectangle.fill", color: .red,
                               destination: AnyView(ECGAnalysisView())),
                AnalyticsEntry(title: "AFib Burden", subtitle: "Daily AFib burden %, 90-day trend & stroke risk context (iOS 16+)", icon: "waveform.path.ecg.rectangle.fill", color: .red,
                               destination: AnyView(AFibBurdenView())),
                AnalyticsEntry(title: "Walking Heart Rate", subtitle: "Passive walking HR as a daily fitness indicator trend", icon: "figure.walk.circle.fill", color: .teal,
                               destination: AnyView(WalkingHeartRateView())),
                AnalyticsEntry(title: "Cardiac Drift", subtitle: "HR drift in long runs — first vs second half aerobic base measure", icon: "arrow.up.right.heart.fill", color: .teal,
                               destination: AnyView(CardiacDriftView())),
                AnalyticsEntry(title: "Aerobic Decoupling Science", subtitle: "Pa:HR physiology, MAF method & heat adaptation — Maffetone 1996: <5% decoupling = aerobic base built; Seiler 2010: 80% Zone 1 volume drives adaptation", icon: "waveform.path", color: .teal,
                               destination: AnyView(AerobicDecouplingScienceView())),
                AnalyticsEntry(title: "Aerobic Decoupling", subtitle: "Pace-to-HR efficiency across long runs — MAF training metric", icon: "waveform.path", color: .teal,
                               destination: AnyView(AerobicDecouplingView())),
                AnalyticsEntry(title: "Hydration Science", subtitle: "Fluid physiology, electrolytes & performance — Sawka 2007: 2% BW loss = 2–4% aerobic drop; Coyle 2004: sodium co-ingestion retains 60% more fluid; Hew-Butler 2015: EAH from over-drinking", icon: "drop.fill", color: .cyan,
                               destination: AnyView(HydrationScienceView())),
                AnalyticsEntry(title: "Nutrition Science", subtitle: "Protein synthesis, CHO metabolism & nutrient timing — Moore 2009: 20g protein maxes MPS; Jentjens 2004: 1.8 g/min CHO with glucose+fructose; Morton 2018: 1.62 g/kg/day optimal", icon: "fork.knife.circle.fill", color: .green,
                               destination: AnyView(NutritionScienceView())),
                AnalyticsEntry(title: "Energy Systems Science", subtitle: "ATP-PCr, glycolytic & aerobic science — Robergs 2004: lactate NOT fatigue cause; Seiler 2010: polarized 80/20; Brooks 2018: Zone 2 & lactate shuttle", icon: "bolt.circle.fill", color: .orange,
                               destination: AnyView(EnergySystemScienceView())),
                AnalyticsEntry(title: "Energy Balance", subtitle: "Radar: aerobic base, threshold, VO₂ max, strength & recovery score", icon: "pentagon.fill", color: .teal,
                               destination: AnyView(EnergySystemBalanceView())),
                AnalyticsEntry(title: "HRV Session Recommender", subtitle: "Today's readiness zone & session suggestions based on HRV vs baseline", icon: "brain.head.profile", color: .green,
                               destination: AnyView(HRVSessionRecommenderView())),
                AnalyticsEntry(title: "HRV Deep Dive", subtitle: "12-month SDNN trend, ANS balance, monthly averages & science", icon: "waveform.path.ecg", color: .green,
                               destination: AnyView(HRVDeepDiveView())),
                AnalyticsEntry(title: "Resting HR Deep Dive", subtitle: "12-month RHR trend, fitness classification & day-of-week pattern", icon: "heart.fill", color: .red,
                               destination: AnyView(RestingHRDeepDiveView())),
                AnalyticsEntry(title: "Workout Goals", subtitle: "Weekly session target, goal streak & sport breakdown over 13 weeks", icon: "trophy.fill", color: .yellow,
                               destination: AnyView(WorkoutGoalTrackerView())),
                AnalyticsEntry(title: "Cycle-Synced Training", subtitle: "Current phase, training tips & performance by menstrual cycle phase", icon: "figure.run.circle.fill", color: .pink,
                               destination: AnyView(CycleTrainingView())),
                AnalyticsEntry(title: "PAI Score", subtitle: "NTNU-validated weekly fitness score — time in HR zones vs 100 PAI longevity target", icon: "waveform.path.ecg.rectangle.fill", color: .green,
                               destination: AnyView(PAIScoreView())),
                AnalyticsEntry(title: "Athlete's Heart", subtitle: "12-month composite: RHR + HRV + VO₂ max adaptation progress & physiology timeline", icon: "heart.fill", color: .red,
                               destination: AnyView(AthletesHeartView())),
                AnalyticsEntry(title: "Cardio Fitness Trajectory", subtitle: "VO₂ max rate of change, 6-month projection & adaptation benchmarks", icon: "chart.line.uptrend.xyaxis.circle.fill", color: .purple,
                               destination: AnyView(CardioFitnessTrajectoryView())),
                AnalyticsEntry(title: "VO₂ Max Trend", subtitle: "Apple Watch VO₂ max estimates, fitness category & 12-month progression", icon: "lungs.fill", color: .purple,
                               destination: AnyView(VO2MaxTrendView())),
                AnalyticsEntry(title: "VO₂ Max vs Age Norms", subtitle: "Compare your VO₂ max against HUNT study age-group percentiles & fitness age", icon: "chart.bar.xaxis.ascending.badge.clock", color: .purple,
                               destination: AnyView(VO2MaxAgeNormsView())),
                AnalyticsEntry(title: "Lactate Threshold Science", subtitle: "Two-threshold physiology, zone training & LT improvement — Faude 2009: LT2 predicts 91% of marathon time variance; Seiler 2010: 80/20 polarized training", icon: "waveform.path.ecg", color: .orange,
                               destination: AnyView(LactateThresholdScienceView())),
                AnalyticsEntry(title: "Lactate Threshold", subtitle: "Estimated LT1 & LT2 from run data — training zones & HR-pace scatter", icon: "waveform.path.ecg", color: .orange,
                               destination: AnyView(LactateThresholdView())),
                AnalyticsEntry(title: "MAS Training Zones", subtitle: "Maximal aerobic speed from VO₂max — personalized pace zones, Billat 2001 interval protocols (vVO₂max)", icon: "gauge.open.with.lines.needle.67percent", color: .orange,
                               destination: AnyView(MASTrainingView())),
                AnalyticsEntry(title: "Heat Acclimatization", subtitle: "Summer training adaptation — Lorenzo 2010: 10-day heat training +4.5% plasma volume, +6.4% VO₂max", icon: "thermometer.sun.fill", color: .orange,
                               destination: AnyView(HeatAcclimatizationView())),
                AnalyticsEntry(title: "Sport-Specific Load", subtitle: "CTL/ATL breakdown per sport — Impellizzeri 2004: pooling across sports masks fatigue & underpreparedness", icon: "figure.mixed.cardio", color: .purple,
                               destination: AnyView(SportSpecificLoadView())),
                AnalyticsEntry(title: "Load vs Performance", subtitle: "Validates whether higher CTL translates to better running efficiency — Bannister 1991 PMC, Lucia 2000 running economy", icon: "chart.dots.scatter", color: .indigo,
                               destination: AnyView(TrainingPerformanceCorrelationView())),
                AnalyticsEntry(title: "Training Polarization", subtitle: "Seiler's 80/20 model — easy vs hard split across all sports with weekly trend", icon: "chart.pie.fill", color: .indigo,
                               destination: AnyView(TrainingPolarizationView())),
                AnalyticsEntry(title: "Critical Speed", subtitle: "Estimated aerobic-anaerobic threshold from run data — CS, D' & training zones", icon: "gauge.with.dots.needle.67percent", color: .teal,
                               destination: AnyView(CriticalSpeedView())),
                AnalyticsEntry(title: "Running Streaks", subtitle: "Current & longest streak, 90-day activity heatmap & weekly frequency", icon: "flame.fill", color: .orange,
                               destination: AnyView(RunningStreakView())),
                AnalyticsEntry(title: "Detraining", subtitle: "Training break detection, Mujika-Padilla VO₂ loss curve & retraining estimates", icon: "arrow.down.heart.fill", color: .red,
                               destination: AnyView(DetrainingView())),
                AnalyticsEntry(title: "State of Mind", subtitle: "Mood valence trend, emotional labels & life-area associations (iOS 18+)", icon: "heart.text.square.fill", color: .pink,
                               destination: AnyView(StateOfMindView())),
            ]
        ),
    ]

    var body: some View {
        List {
            ForEach(sections, id: \.header) { section in
                Section(section.header) {
                    ForEach(section.entries) { entry in
                        NavigationLink(destination: entry.destination) {
                            HStack(spacing: 12) {
                                Image(systemName: entry.icon)
                                    .font(.title3)
                                    .foregroundStyle(entry.color)
                                    .frame(width: 36, height: 36)
                                    .background(entry.color.opacity(0.12))
                                    .clipShape(RoundedRectangle(cornerRadius: 8))

                                VStack(alignment: .leading, spacing: 2) {
                                    Text(entry.title)
                                        .font(.subheadline.weight(.medium))
                                    Text(entry.subtitle)
                                        .font(.caption)
                                        .foregroundStyle(.secondary)
                                }
                            }
                            .padding(.vertical, 4)
                        }
                    }
                }
            }
        }
        .listStyle(.insetGrouped)
        .navigationTitle("Analytics")
        .navigationBarTitleDisplayMode(.inline)
    }
}

#Preview {
    NavigationStack {
        WorkoutAnalyticsView()
    }
}
