'use client'
import { useState } from 'react'

export default function ExportPage() {
  const [from, setFrom] = useState(() => {
    const d = new Date(); d.setDate(d.getDate() - 30)
    return d.toISOString().split('T')[0]
  })
  const [to, setTo] = useState(() => new Date().toISOString().split('T')[0])
  const [loading, setLoading] = useState(false)

  async function generatePDF() {
    setLoading(true)
    try {
      const res = await fetch(`/api/export/pdf?from=${from}&to=${to}`)
      const data = await res.json()

      // Dynamic import jspdf to avoid SSR issues
      const { jsPDF } = await import('jspdf')
      // @ts-ignore
      const autoTable = (await import('jspdf-autotable')).default

      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      
      // Header
      doc.setFontSize(22)
      doc.setTextColor(99, 102, 241) // indigo
      doc.text('KQuarks Health Report', 20, 25)
      
      doc.setFontSize(10)
      doc.setTextColor(100, 100, 100)
      doc.text(`Period: ${data.period.from} to ${data.period.to}`, 20, 33)
      doc.text(`Generated: ${new Date(data.generated_at).toLocaleDateString()}`, 20, 39)

      // Summary box
      doc.setFontSize(12)
      doc.setTextColor(30, 30, 30)
      doc.text('Summary', 20, 52)
      doc.setFontSize(10)
      doc.setTextColor(80, 80, 80)
      doc.text(`• Total days tracked: ${data.summary.total_days}`, 25, 59)
      doc.text(`• Health metric readings: ${data.summary.metrics_recorded}`, 25, 65)
      doc.text(`• Sleep sessions recorded: ${data.summary.sleep_sessions}`, 25, 71)
      doc.text(`• Active medications: ${data.summary.active_medications}`, 25, 77)

      // Health Metrics table
      if (data.health_metrics.length > 0) {
        doc.setFontSize(12)
        doc.setTextColor(30, 30, 30)
        doc.text('Health Metrics', 20, 92)
        
        const metricsRows = data.health_metrics.slice(0, 50).map((m: Record<string, unknown>) => [
          m.recorded_at ? new Date(m.recorded_at as string).toLocaleDateString() : '',
          String(m.metric_type || ''),
          String(m.value || ''),
          String(m.unit || ''),
        ])
        
        autoTable(doc, {
          startY: 96,
          head: [['Date', 'Metric', 'Value', 'Unit']],
          body: metricsRows,
          styles: { fontSize: 9 },
          headStyles: { fillColor: [99, 102, 241] },
          margin: { left: 20, right: 20 },
        })
      }

      // Sleep table
      if (data.sleep_records.length > 0) {
        const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? 100
        doc.setFontSize(12)
        doc.setTextColor(30, 30, 30)
        doc.text('Sleep Records', 20, finalY + 15)
        
        const sleepRows = data.sleep_records.slice(0, 30).map((s: Record<string, unknown>) => [
          s.sleep_start ? new Date(s.sleep_start as string).toLocaleDateString() : '',
          s.duration_minutes ? `${Math.round((s.duration_minutes as number) / 60 * 10) / 10}h` : '-',
          String(s.quality_score || '-'),
          String(s.sleep_stage || '-'),
        ])
        
        autoTable(doc, {
          startY: finalY + 19,
          head: [['Date', 'Duration', 'Quality Score', 'Stage']],
          body: sleepRows,
          styles: { fontSize: 9 },
          headStyles: { fillColor: [99, 102, 241] },
          margin: { left: 20, right: 20 },
        })
      }

      // Medications
      if (data.medications.length > 0) {
        const finalY2 = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? 150
        doc.setFontSize(12)
        doc.setTextColor(30, 30, 30)
        doc.text('Active Medications', 20, finalY2 + 15)
        
        autoTable(doc, {
          startY: finalY2 + 19,
          head: [['Medication', 'Dosage', 'Frequency']],
          body: data.medications.map((m: Record<string, unknown>) => [
            String(m.name || ''),
            String(m.dosage || '-'),
            String(m.frequency || '-'),
          ]),
          styles: { fontSize: 9 },
          headStyles: { fillColor: [99, 102, 241] },
          margin: { left: 20, right: 20 },
        })
      }

      // Footer
      const pageCount = doc.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(150, 150, 150)
        doc.text('This report is for personal reference only. Consult your healthcare provider for medical advice.', 20, 287)
        doc.text(`Page ${i} of ${pageCount} | Generated by KQuarks`, 20, 292)
      }

      doc.save(`KQuarks_Health_Report_${from}_to_${to}.pdf`)
    } catch (err) {
      console.error('PDF generation failed:', err)
      alert('Could not generate PDF. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-background p-4 max-w-lg mx-auto">
      <h1 className="text-2xl font-bold text-text-primary mb-2">Export Health Report</h1>
      <p className="text-text-secondary text-sm mb-6">Generate a PDF summary to share with your doctor or keep for your records.</p>

      <div className="bg-surface border border-border rounded-2xl p-5 mb-4 space-y-4">
        <h2 className="font-semibold text-text-primary">Select Date Range</h2>
        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className="block text-xs text-text-secondary mb-1">From</label>
            <input type="date" value={from} onChange={e => setFrom(e.target.value)}
              className="w-full bg-background border border-border rounded-xl px-3 py-2 text-text-primary text-sm" />
          </div>
          <div>
            <label className="block text-xs text-text-secondary mb-1">To</label>
            <input type="date" value={to} onChange={e => setTo(e.target.value)}
              className="w-full bg-background border border-border rounded-xl px-3 py-2 text-text-primary text-sm" />
          </div>
        </div>
        <div className="flex gap-2 flex-wrap">
          {[['Last 7 days', 7], ['Last 30 days', 30], ['Last 90 days', 90]].map(([label, days]) => (
            <button key={label} onClick={() => {
              const t = new Date(); const f = new Date(); f.setDate(f.getDate() - (days as number))
              setTo(t.toISOString().split('T')[0]); setFrom(f.toISOString().split('T')[0])
            }} className="px-3 py-1.5 rounded-xl border border-border text-xs text-text-secondary hover:bg-surface-secondary transition-colors">
              {label}
            </button>
          ))}
        </div>
      </div>

      <div className="bg-surface border border-border rounded-2xl p-5 mb-4">
        <h2 className="font-semibold text-text-primary mb-3">Report Includes</h2>
        <ul className="space-y-2 text-sm text-text-secondary">
          {['📊 Health metrics (steps, HR, HRV, weight)', '😴 Sleep records', '💊 Active medications', '📋 Summary statistics'].map(item => (
            <li key={item} className="flex items-center gap-2">{item}</li>
          ))}
        </ul>
      </div>

      <button onClick={generatePDF} disabled={loading}
        className="w-full py-3.5 bg-primary text-white rounded-2xl font-semibold text-base disabled:opacity-50 flex items-center justify-center gap-2">
        {loading ? '⏳ Generating...' : '📄 Download PDF Report'}
      </button>
      <p className="text-xs text-text-secondary mt-3 text-center">For personal reference only. Not a medical document.</p>
    </div>
  )
}
