name: Web Deploy

on:
  push:
    branches: [main]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [main]
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_sZRvQF9f2uqbr8UkQcW7xuuH
          vercel-project-id: prj_yqVjHRnPpy6HvHqJwP4gDgz57Tkb
          vercel-args: '--prod'
          working-directory: web
